# Site settings
title: JCLFARMS
email: jimmy@jclfarms.com
description: "Handcrafted wooden bowls and cutting boards"
baseurl: ""
url: "http://www.jclfarms.com"
twitter_username: jclfarms

# Build settings
markdown: kramdown
permalink: pretty
